### ISSUE TITLE
[rollup-plugin-dynamic-import-variables] Assigning to rvalue (1:2)

### ISSUE THREAD

**Issue by dubs3c** [LarsDenBakker/rollup-plugin-dynamic-import-variables#11]
Hi!

I'm unsure if this is the correct place to submit an issue, but I thought I'll try here first. I'm trying to build my static website using Sveltekit, but I get this error when building the project:

```
[rollup-plugin-dynamic-import-variables] Assigning to rvalue (1:2)
file: /Users/user/Sites/website/src/posts/myfile.md:1:2
> Assigning to rvalue (1:2)
SyntaxError: Assigning to rvalue (1:2)
    at Parser.pp$4.raise (/Users/user/Sites/website/node_modules/rollup/dist/shared/rollup.js:16958:13)
    at Parser.pp$2.checkLValSimple (/Users/user/Sites/website/node_modules/rollup/dist/shared/rollup.js:15820:10)
    at Parser.pp$3.parseMaybeUnary (/Users/user/Sites/website/node_modules/rollup/dist/shared/rollup.js:16087:24)
    at Parser.pp$3.parseExprOps (/Users/user/Sites/website/node_modules/rollup/dist/shared/rollup.js:16029:19)
    at Parser.pp$3.parseMaybeConditional (/Users/user/Sites/website/node_modules/rollup/dist/shared/rollup.js:16012:19)
    at Parser.pp$3.parseMaybeAssign (/Users/user/Sites/website/node_modules/rollup/dist/shared/rollup.js:15980:19)
    at Parser.pp$3.parseExpression (/Users/user/Sites/website/node_modules/rollup/dist/shared/rollup.js:15944:19)
    at Parser.pp$1.parseStatement (/Users/user/Sites/website/node_modules/rollup/dist/shared/rollup.js:14656:45)
    at Parser.pp$1.parseTopLevel (/Users/user/Sites/website/node_modules/rollup/dist/shared/rollup.js:14523:21)
    at Parser.parse (/Users/user/Sites/website/node_modules/rollup/dist/shared/rollup.js:14315:15)
```

Something is trying to parse my markdown file, but fails. So my question is, how do I exclude `.md` files so that I can build my project?

Versions I am using:
```
node version: v14.17.3
npm version: 6.14.13
rollup version: 2.56.3 (as seen in package-lock.json)
```

**Comment by dubs3c** [comment]
Finally solved the error, was a third-party script doing weird shit.
